<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="1" failures="0" finished="true" name="Test Run: 5" tests="0" total_time="Finished in: 0.00 secs."/>
    <test location="C:/Users/tscal/Desktop/UMGC/SDEV 300/Lab4/lab4/numpy_lab.py" status="error" test="lab4.numpy_lab" time="0">
        <stdout/>
        <stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\tscal\.p2\pool\plugins\org.python.pydev.core_11.0.0.202310081318\pysrc\_pydev_runfiles\pydev_runfiles.py", line 460, in __get_module_from_str
    mod = __import__(modname)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tscal\Desktop\UMGC\SDEV 300\Lab4\lab4\numpy_lab.py", line 12, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
ERROR: Module: lab4.numpy_lab could not be imported (file: C:/Users/tscal/Desktop/UMGC/SDEV 300/Lab4/lab4/numpy_lab.py).
]]></stderr>
    </test>
    <launch mode="run">
        <launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Lab4 Lab4"/>
]]></launch_memento>
    </launch>
</pydev-testsuite>
